pipeline:
  name: remotechild
  identifier: remotechild
  projectIdentifier: newqajt
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: remotstag
        identifier: remotstag
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorAxNW3X7QRK
              namespace: harness-qa-delegate
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.CItestDockerConnector7NLm559raP
                    image: alpine
                    shell: Sh
                    command: echo jkgskad
