pipeline:
  name: remotepip
  identifier: remotepip
  projectIdentifier: newqajt
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: remotechild
        identifier: remotechild
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remotechild
          project: newqajt
    - stage:
        name: basic
        identifier: basic
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: retry_failed
          project: newqajt
          inputs:
            identifier: retry_failed
            stages:
              - stage:
                  identifier: first
                  type: CI
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: Run_1
                            type: Run
                            spec:
                              image: <+input>
          outputs: []
        when:
          pipelineStatus: Success
          condition: "false"
    - stage:
        name: sdfs
        identifier: sdfs
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorAxNW3X7QRK
              namespace: harness-qa-delegate
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.CItestDockerConnector7NLm559raP
                    image: alpine
                    shell: Sh
                    command: echo jksfhfk
    - stage:
        name: ada
        identifier: ada
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: aaa
          environment:
            environmentRef: prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
