pipeline:
  name: remotepip
  identifier: remotepip
  projectIdentifier: newqajt
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: child1
        identifier: child1
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: retry_failed
          project: newqajt
          inputs:
            identifier: retry_failed
            stages:
              - stage:
                  identifier: first
                  type: CI
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: Run_1
                            type: Run
                            spec:
                              image: <+input>
