pipeline:
  name: remotepip
  identifier: remotepip
  projectIdentifier: newqajt
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: remotechild
        identifier: remotechild
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remotechild
          project: newqajt
          outputs:
            - name: out1
              value: "false"
    - stage:
        name: basic
        identifier: basic
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: retry_failed
          project: newqajt
          inputs:
            identifier: retry_failed
            stages:
              - stage:
                  identifier: first
                  type: CI
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: Run_1
                            type: Run
                            spec:
                              image: <+input>
          outputs: []
        when:
          pipelineStatus: Success
    - stage:
        name: sdfs
        identifier: sdfs
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorAxNW3X7QRK
              namespace: harness-qa-delegate
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.CItestDockerConnector7NLm559raP
                    image: alpine
                    shell: Sh
                    command: echo jksfhfk
